name: masstamilan_downloader
description: A mobile app to bulk download MP3s from Masstamilan.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  file_picker: ^8.1.4
  csv: ^6.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  dio: ^5.3.3
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
